<!DOCTYPE html>
<html>
<head>
	<title>Texyla</title>
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8">

	<style type="text/css">
	body {
		font: 80%/1.3em "Segoe UI", sans-serif;
	}
	</style>

	<link rel="shortcut icon" href="{$basePath}/favicon.png" type="image/png">

	<link rel="stylesheet" href="../../../texyla/css/style.css" type="text/css">
	<link rel="stylesheet" href="../../../themes/default/theme.css" type="text/css">

	<!-- jQuery -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" type="text/javascript"></script>
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css" type="text/css">

	<!-- JUSH -->
	<script src="https://jush.svn.sourceforge.net/svnroot/jush/trunk/jush.js" type="text/javascript"></script>
	<link rel="stylesheet" type="text/css" href="https://jush.svn.sourceforge.net/svnroot/jush/trunk/jush.css">

	{widget texyla}
</head>
<body>
	{include #content}
</body>
</html>
