<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<title>Texyla</title>
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8">

	<style type="text/css">
	body {
		font: 80%/1.3em "Segoe UI", sans-serif;
	}
	</style>

	<link rel="stylesheet" href="../../../texyla/css/style.css" type="text/css">
	<link rel="stylesheet" href="../../../themes/default/theme.css" type="text/css">

	<!-- jQuery -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" type="text/javascript"></script>
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css" type="text/css">

	<!-- JUSH -->
	<script src="https://jush.svn.sourceforge.net/svnroot/jush/trunk/jush.js"></script>
	<link rel="stylesheet" type="text/css" href="https://jush.svn.sourceforge.net/svnroot/jush/trunk/jush.css">

	<!-- Texyla core -->
	<script src="../../../texyla/js/texyla.js" type="text/javascript"></script>
	<script src="../../../texyla/js/selection.js" type="text/javascript"></script>
	<script src="../../../texyla/js/texy.js" type="text/javascript"></script>
	<script src="../../../texyla/js/buttons.js" type="text/javascript"></script>
	<script src="../../../texyla/js/dom.js" type="text/javascript"></script>
	<script src="../../../texyla/js/view.js" type="text/javascript"></script>
	<script src="../../../texyla/js/ajaxupload.js" type="text/javascript"></script>

	<!-- languages -->
	<script src="../../../texyla/languages/cs.js" type="text/javascript"></script>
	<script src="../../../texyla/languages/sk.js" type="text/javascript"></script>
	<script src="../../../texyla/languages/en.js" type="text/javascript"></script>

	<!-- plugins -->
	<script src="../../../texyla/plugins/keys/keys.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/window/window.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/resizableTextarea/resizableTextarea.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/img/img.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/table/table.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/link/link.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/emoticon/emoticon.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/symbol/symbol.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/files/files.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/color/color.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/textTransform/textTransform.js" type="text/javascript"></script>
	<script src="../../../texyla/plugins/youtube/youtube.js" type="text/javascript"></script>

	<!-- init -->
	<script type="text/javascript">
		//<![CDATA[

		$.texyla.setDefaults({
			texyCfg: "admin",
			baseDir: {$baseUri} + '../../../texyla',
			previewPath: {plink Texyla:preview},
			filesPath: {plink Texyla:listFiles},
			filesThumbPath: '%var%',
			filesUploadPath: {plink Texyla:upload}
		});

		$(function () {
			$(".texyla").texyla({
				toolbar: [
					'h1', 'h2', 'h3', 'h4',
					null,
					'bold', 'italic',
					null,
					'center', ['left', 'right', 'justify'],
					null,
					'ul', 'ol', ["olAlphabetSmall", "olAlphabetBig", "olRomans", "olRomansSmall"],
					null,
					{ type: "label", text: "Vložit"}, 'link', 'img', 'table', 'emoticon', 'symbol',
					null,
					'color', 'textTransform',
					null,
					'files', 'youtube',
					null,
					'div', ['html', 'blockquote', 'text', 'comment'],
					null,
					'code',	['codeHtml', 'codeCss', 'codeJs', 'codePhp', 'codeSql'], 'codeInline',
					null,
					{ type: "label", text: "Ostatní"}, ['sup', 'sub', 'del', 'acronym', 'hr', 'notexy', 'web']

				],
				texyCfg: "admin",
				bottomLeftToolbar: ['edit', 'preview', 'htmlPreview'],
				buttonType: "span",
				tabs: true
			});

			$.texyla({
				buttonType: "button"
			});

		});
		//]]>
	</script>
</head>
<body>
	{include #content}
</body>
</html>
