{* http://phpfashion.com/how-to-correctly-insert-a-flash-into-xhtml *}
<!--[if !IE]> -->
<object type="application/x-shockwave-flash" data="{$url}" width="{$width}" height="{$height}">
<!-- <![endif]-->

<!--[if IE]>
<object
	classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
	codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0"
	width="{$width}"
	height="{$height}">
	<param name="movie" value="{$url}">
<!--><!--dgx-->
	<param name="loop" value="true">
	<param name="menu" value="false">
	<param name="wmode" value="opaque">

	{ifset $title}<p>{$title}</p>{/if}
</object>
<!-- <![endif]-->